# Generated by Django 5.0.1 on 2024-02-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_booking", "0003_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
